name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Plugin version'
        required: true
        type: string
      targetAbi:
        description: 'Target Jellyfin version'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Set up .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x
    - name: Dotnet publish
      run: |
        dotnet restore --no-http-cache
        dotnet publish --no-restore --configuration=Release --framework=net10.0 -p:Version=${{ inputs.version }}
    - name: Zip
      run: |
        cd Jellyfin.Plugin.TorrentTags/bin/Release/net10.0/publish
        zip -r torrent-tags_${{ inputs.version }}.zip .
    - name: Create GitHub release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create v${{ inputs.version }} Jellyfin.Plugin.TorrentTags/bin/Release/net10.0/publish/torrent-tags_${{ inputs.version }}.zip -t ${{ inputs.version }} --generate-notes
    - name: Update manifest
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        jq \
          --arg version "${{ inputs.version }}" \
          --arg changelog "$(gh release view v${{ inputs.version }} --json body --jq '.body')" \
          --arg targetAbi "${{ inputs.targetAbi }}" \
          --arg sourceUrl "https://github.com/${{ github.repository }}/releases/download/v${{ inputs.version }}/torrent-tags_${{ inputs.version }}.zip" \
          --arg checksum "$(md5sum Jellyfin.Plugin.TorrentTags/bin/Release/net10.0/publish/torrent-tags_${{ inputs.version }}.zip | cut -d ' ' -f 1)" \
          --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          '.[0].versions += [{
            version: $version,
            changelog: $changelog,
            targetAbi: $targetAbi,
            sourceUrl: $sourceUrl,
            checksum: $checksum,
            timestamp: $timestamp
          }]' \
          manifest.json > manifest.json.tmp
        mv manifest.json.tmp manifest.json
    - name: Commit manifest
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add manifest.json
        git commit -m "Add v${{ inputs.version }} to manifest"
        git push
